イベント開催会場を「株式会社インプレス」に更新
inamasa12/ichiyasaGitSample pull request #1
Opened 2023-03-31 11:36 UTC by inamasa12

### 変更内容
イベント開催会場を「株式会社インプレス」に変更しました。

### 背景
「株式会社インプレス」さんがイベント会場を提供してくださることになりました。

2023-04-01 06:59 UTC, inamasa12 commented
修正ありがとうございます！問題がないのでマージします。

2023-04-01 07:02 UTC, masaina21 commented
修正ありがとうございます！問題ないのでマージします。

2023-04-01 23:53 UTC, masaina21 requested changes
修正したい箇所がありましたので、ご確認と修正をお願いします。

2023-04-01 23:53 UTC, masaina21 commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
「株式会社」を(株)に変更して頂けますか？

2023-04-02 00:17 UTC, inamasa12 commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
修正したものをプッシュしたので、再度ご確認ください。

2023-04-02 00:21 UTC, masaina21 commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
ありがとうございます❕

2023-04-03 11:33 UTC, masaina21 approved these changes

2023-04-03 11:56 UTC, merged